name: On PR Merged - Update weekly & README

on:
  pull_request:
    types: [closed]
    branches: [main]  # mainにマージされた時だけ起動

jobs:
  on-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine changed entry file path
        id: files
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request.number;
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr,
            });
            const entryFiles = files
              .map(f => f.filename)
              .filter(p => /^entries\/\d{4}\/\d{4}-\d{2}-\d{2}\.md$/.test(p));
            if (!entryFiles.length) {
              core.setFailed('No daily entry file found (expected entries/YYYY/YYYY-MM-DD.md)');
            }
            entryFiles.sort().reverse(); // 一番新しい日付を採用
            core.setOutput('entry', entryFiles[0]);

      - name: Update weekly.md and README.md
        id: update
        shell: bash
        run: |
          set -euxo pipefail
          ENTRY_PATH="${{ steps.files.outputs.entry }}"
          ENTRY_FILE="$(basename "$ENTRY_PATH")"      # e.g. 2025-10-02.md
          ENTRY_DATE="${ENTRY_FILE%.md}"              # e.g. 2025-10-02

          # weekly.mdがなければ初期化
          if [ ! -f weekly.md ]; then
            printf "# 今週の振り返り\n\n" > weekly.md
          fi

          # weekly.md 末尾に追記（重複防止）
          LINE="- [${ENTRY_DATE} の振り返り](${ENTRY_PATH})"
          (grep -qxF "$LINE" weekly.md) || echo "$LINE" >> weekly.md

          # READMEのプレースホルダを最新リンクで置換
          # READMEに必ず以下の文字列を入れておくこと：
          #   <!-- LAST_ENTRY_LINK -->
          if [ ! -f README.md ]; then
            printf "# Daily Reflection\n\n## 最新の振り返り\n<!-- LAST_ENTRY_LINK -->\n" > README.md
          fi
          perl -0777 -pe "s|<!-- LAST_ENTRY_LINK -->.*|<!-- LAST_ENTRY_LINK --> - [${ENTRY_DATE} の振り返り](${ENTRY_PATH})|s" -i README.md

          echo "entry_date=${ENTRY_DATE}" >> $GITHUB_OUTPUT
          echo "entry_path=${ENTRY_PATH}" >> $GITHUB_OUTPUT

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update weekly & README for ${{ steps.update.outputs.entry_date }}"
          file_pattern: |
            weekly.md
            README.md
